# -*- coding: utf-8 -*-
"""安全知识库 —— 整合自 gbt-codeagent 项目的知识体系。

包含：CWE 分类、漏洞模式、OWASP 映射、GB/T 国标映射、语言审计规则、
漏洞评分体系、证据点定义、组件漏洞规则等。
"""
from src.knowledge.vulnerability_patterns import VULNERABILITY_PATTERNS, ALL_VULNERABILITY_DOCS
from src.knowledge.owasp_mapping import OWASP_MAPPING, OWASP_NAMES
from src.knowledge.gbt_standards import GBT_STANDARDS, VULN_GBT_MAP, LANGUAGE_GBT_MAP
from src.knowledge.vuln_scoring import (
    REACHABILITY_LEVELS,
    IMPACT_LEVELS,
    COMPLEXITY_LEVELS,
    SEVERITY_LEVELS,
    VULN_TYPE_CODES,
    score_vulnerability,
    score_from_reference,
    get_vuln_type_defaults,
    VulnIdGenerator,
    generate_vuln_stats_table,
)
from src.knowledge.evidence_points import EVIDENCE_POINTS
from src.knowledge.language_audit_rules import LANGUAGE_AUDIT_RULES, LANGUAGE_VULN_MAP
from src.knowledge.audit_config import (
    FILE_EXTENSION_MAP,
    LANGUAGE_EXTENSIONS,
    VULN_CWE_MAP,
    COMPONENT_VULN_RULES,
    AUDIT_PROFILES,
    SEVERITY_LEVELS,
    GUIDELINE_REFERENCES,
    ANALYSIS_OPTIONS,
    AUDIT_SCHEDULING,
    detect_language,
    is_vulnerability_supported,
    get_vuln_type_code,
    generate_vuln_id,
    calculate_dktss,
    get_dktss_severity,
)
from src.knowledge.audit_skills import AUDIT_SKILLS, AUDIT_WORKFLOW, QUALITY_STANDARDS, COMBINED_VULN_PATTERNS, LINE_VERIFICATION_FLOW
from src.knowledge.framework_rules import (
    FRAMEWORK_RULES,
    LANGUAGE_ADAPTERS,
    FRAMEWORK_DOCS,
    detect_framework,
    get_framework_vulns,
    get_language_adapter,
    get_control_patterns,
    get_dangerous_patterns,
    get_framework_configs,
    get_route_annotations,
)
from src.knowledge.security_domains import (
    UNIVERSAL_SECURITY_HINTS,
    SECURITY_DOMAINS,
    QUICK_GREP_RULES,
    REAL_WORLD_VULNS,
    SECURITY_DOMAIN_DOCS,
    get_domain_checks,
    get_grep_rules,
    get_real_world_vuln,
    search_vulns_by_component,
)
from src.knowledge.audit_prompts import (
    REVIEW_PRIORITY_LAYERS,
    CORE_SECURITY_PRINCIPLES,
    RUNTIME_CONTEXT_AWARENESS,
    SEVERITY_CLASSIFICATION_GUIDE,
    FILE_VALIDATION_RULES,
    EVIDENCE_CONTRACT_GUIDE,
    DE_DUPLICATION_RULES,
    DUAL_VERDICT_SYSTEM,
    LANGUAGE_AUDIT_RULES_LLM,
    build_audit_system_prompt,
)
from src.knowledge.detection_patterns import (
    DETECTION_PATTERNS,
    SECURITY_CHECKLIST,
    LANGUAGE_CHECKLISTS,
    SINK_EVIDENCE_TEMPLATES,
    get_detection_patterns,
    format_detection_patterns_for_prompt,
    get_language_checklist,
    get_evidence_template,
)
from src.knowledge.gbt_standards import GBT_EVIDENCE_REQUIREMENTS
from src.knowledge.audit_vulnerability_guides import (
    get_vulnerability_guide,
    SQL_INJECTION_GUIDE,
    COMMAND_INJECTION_GUIDE,
    DESERIALIZATION_GUIDE,
    CODE_INJECTION_GUIDE,
    WEAK_CRYPTO_GUIDE,
    HARDCODED_CREDENTIALS_GUIDE,
    PATH_TRAVERSAL_GUIDE,
    VULN_GUIDE_MAP,
    VULN_NAME_TO_GUIDE,
)
from src.knowledge.audit_scoring import (
    calculate_audit_score,
    generate_audit_report,
    GATE_THRESHOLDS,
    GRADE_RANGES,
)
from src.knowledge.component_vulns import (
    COMPONENT_VULNS,
    check_component_vuln,
    get_all_component_vuln_names,
    format_component_vulns_for_prompt,
)

__all__ = [
    "VULNERABILITY_PATTERNS",
    "ALL_VULNERABILITY_DOCS",
    "OWASP_MAPPING",
    "OWASP_NAMES",
    "GBT_STANDARDS",
    "VULN_GBT_MAP",
    "LANGUAGE_GBT_MAP",
    "REACHABILITY_LEVELS",
    "IMPACT_LEVELS",
    "COMPLEXITY_LEVELS",
    "SEVERITY_LEVELS",
    "VULN_TYPE_CODES",
    "score_vulnerability",
    "score_from_reference",
    "get_vuln_type_defaults",
    "VulnIdGenerator",
    "generate_vuln_stats_table",
    "EVIDENCE_POINTS",
    "LANGUAGE_AUDIT_RULES",
    "LANGUAGE_VULN_MAP",
    "FILE_EXTENSION_MAP",
    "LANGUAGE_EXTENSIONS",
    "VULN_CWE_MAP",
    "COMPONENT_VULN_RULES",
    "AUDIT_PROFILES",
    "SEVERITY_LEVELS",
    "GUIDELINE_REFERENCES",
    "ANALYSIS_OPTIONS",
    "AUDIT_SCHEDULING",
    "detect_language",
    "is_vulnerability_supported",
    "get_vuln_type_code",
    "generate_vuln_id",
    "calculate_dktss",
    "get_dktss_severity",
    "AUDIT_SKILLS",
    "AUDIT_WORKFLOW",
    "QUALITY_STANDARDS",
    "COMBINED_VULN_PATTERNS",
    "LINE_VERIFICATION_FLOW",
    "FRAMEWORK_RULES",
    "LANGUAGE_ADAPTERS",
    "FRAMEWORK_DOCS",
    "detect_framework",
    "get_framework_vulns",
    "get_language_adapter",
    "get_control_patterns",
    "get_dangerous_patterns",
    "get_framework_configs",
    "get_route_annotations",
    "UNIVERSAL_SECURITY_HINTS",
    "SECURITY_DOMAINS",
    "QUICK_GREP_RULES",
    "REAL_WORLD_VULNS",
    "SECURITY_DOMAIN_DOCS",
    "get_domain_checks",
    "get_grep_rules",
    "get_real_world_vuln",
    "search_vulns_by_component",
    "REVIEW_PRIORITY_LAYERS",
    "CORE_SECURITY_PRINCIPLES",
    "RUNTIME_CONTEXT_AWARENESS",
    "SEVERITY_CLASSIFICATION_GUIDE",
    "FILE_VALIDATION_RULES",
    "EVIDENCE_CONTRACT_GUIDE",
    "DE_DUPLICATION_RULES",
    "DUAL_VERDICT_SYSTEM",
    "LANGUAGE_AUDIT_RULES_LLM",
    "build_audit_system_prompt",
    "DETECTION_PATTERNS",
    "SECURITY_CHECKLIST",
    "LANGUAGE_CHECKLISTS",
    "SINK_EVIDENCE_TEMPLATES",
    "get_detection_patterns",
    "format_detection_patterns_for_prompt",
    "get_language_checklist",
    "get_evidence_template",
    "GBT_EVIDENCE_REQUIREMENTS",
    "calculate_audit_score",
    "generate_audit_report",
    "GATE_THRESHOLDS",
    "GRADE_RANGES",
    "COMPONENT_VULNS",
    "check_component_vuln",
    "get_all_component_vuln_names",
    "format_component_vulns_for_prompt",
]
